# Docker compose file

networks:
  homelab_macvlan:
    external: true

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    networks:
      homelab_macvlan:
        ipv4_address: 192.168.0.2
    environment:
      TZ: "America/Phoenix"
      WEBPASSWORD: "Skywalk101"
      DNSMASQ_LISTENING: all
#      FTLCONF_LOCAL_IPV4: 192.168.0.9
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped

  minecraft:
    image: itzg/minecraft-server:latest
    container_name: minecraft
    networks:
      homelab_macvlan:
        ipv4_address: 192.168.50.50
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: "LATEST"
      MOTD: "Welcome to Naturedome"
      MAX_PLAYERS: 3
#    dns:
#      - 192.168.0.9  #pihole
#      - 1.1.1.1       #fallback
    volumes:
      - ./minecraft/data:/data
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      homelab_macvlan:
        ipv4_address: 192.168.0.3
    ports:
      - "8080:80"
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/html:/user/share/nginx/html
      - ./gins/conf.d:/etc/nginx/conf.d
    restart: unless-stopped

  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    networks:
      homelab_macvlan:
        ipv4_address: 192.168.0.5
    ports:
      - "7575:7575"
    volumes:
      - ./homarr/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SECRET_ENCRYPTION_KEY=876153e49723f97203b33c57c85ccb4369af79bfde56b88a33128f402e680c01
    restart: unless-stopped
