services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - ./homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=9c862d3af14b5daa99b98e40f7b2d6fa8f18f032dc58a1b5c931daa883e191e1
    ports:
      - '7575:7575'
    dns:
      - 192.168.0.9
    dns_search:
      - google.com
