services:
  mc:
    image: itzg/minecraft-server
    container_name: mc-vanilla
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    dns:
      - "192.168.0.9"
    networks:
      custom_bridge:
        ipv4_address: 192.168.0.5
    environment:
      EULA: "TRUE"
      OPS: "IrAnSov"
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data
    restart: unless-stopped

networks:
  custom_bridge:
    name: minecraft_net
    external: true
